### ISSUE TITLE
Research on cool and short share form like wordle

### ISSUE THREAD

**Issue by HuangJunye** [QPong/planning#2]

**Comment by Unathi-Skosana** [comment]
## How to implement?

- Get end game data from several rounds of a QPong game (i.e. scores, mode, etc.)
- Nicely format endgame data (emojis like wordle?)
- Interact with a social media API [meta](https://developers.facebook.com/docs/sharing/) and [twitter](https://developer.twitter.com/en/docs/twitter-for-websites) to post on behalf of user.
- Alternatively, one can just copy the formatted data to the user's clipboard (`navigator.clipboard.writeText(...)`).

## Which option is better?
- I have a preference for the latter option (copying to clipboard), for the sake simplicity (no interactions with external API) and versatility (clipboard copied text can be posted on any platform of the user's choice)

**Comment by HuangJunye** [comment]
@Unathi-Skosana can you please add the link to the codepen demo you showed during the meeting here? After that I can close the issue.

**Comment by HuangJunye** [comment]
Sorry just saw that you have made the edit. Thank you!
