### ISSUE TITLE
Understand QPong code written in PICO-8: qpong.p8

### ISSUE THREAD

**Issue by HuangJunye** [QPong/planning#20]

**Comment by tula3and** [comment]
- To make a .p8 program, should I have to buy it first? - [PICO-8](https://www.lexaloffle.com/pico-8.php)
- Good PICO-8 reference: [PICO-8 - Game Design and Development](https://eugene.libguides.com/gamedesign/pico8)
- Reference of Qiskit code for PICO-8?

**Comment by tula3and** [comment]
- [PICO-8 Education Edition](https://www.pico-8-edu.com/): drag and drop the file - type `run`
- [qiskit-community/MicroQiskit](https://github.com/qiskit-community/MicroQiskit)
